### ISSUE TITLE
TypeError: tree_map() missing 1 required positional argument: 'tree'

### ISSUE THREAD

**Issue by unnaturalyianni** [sokrypton/ColabDesign#70]
Hello!

I am running the following script for binder hallucination:

```
from colabdesign import mk_af_model

model = mk_af_model(protocol="binder")
model.prep_inputs(pdb_filename=target, binder_len=10)
model.design_3stage(100, 100, 10)
```
and i am getting the following error:

```
/home/yianni/.cache/pypoetry/virtualenvs/colabdesign-ho_SLdon-py3.8/lib/python3.8/site-packages/dm_haiku-0.0.7-py3.8.egg/haiku/_src/data_structures.py:37: FutureWarning: jax.tree_structure is deprecated, and will be removed in a future release. Use jax.tree_util.tree_structure instead.
  PyTreeDef = type(jax.tree_structure(None))
2022-09-01 23:34:49.083349: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-09-01 23:34:49.675704: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-09-01 23:34:49.675780: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-09-01 23:34:49.675793: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-09-01 23:34:50.497173: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2022-09-01 23:34:50.497203: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
ERROR: alphafold params not found
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    model.design_3stage(100, 100, 10)
  File "/home/yianni/ColabDesign/colabdesign/af/design.py", line 393, in design_3stage
    self.design_logits(soft_iters, e_soft=1, **kwargs)
  File "/home/yianni/ColabDesign/colabdesign/af/design.py", line 366, in design_logits
    self.design(iters, **kwargs)
  File "/home/yianni/ColabDesign/colabdesign/af/design.py", line 361, in design
    self.step(lr_scale=lr_scale, backprop=backprop, repredict=repredict,
  File "/home/yianni/ColabDesign/colabdesign/af/design.py", line 193, in step
    self.run(backprop=backprop, callback=callback)
  File "/home/yianni/ColabDesign/colabdesign/af/design.py", line 105, in run
    aux = jax.tree_map(lambda *x: jnp.stack(x), *aux)
TypeError: tree_map() missing 1 required positional argument: 'tree'
```

Please let me know what I should do!

Thank you for your time.

**Comment by sokrypton** [comment]
hmmm, does this happen with other protocol, or just the binder example?

Can you share the example you used? (you can email me at so@fas.harvard.edu if private).

**Comment by unnaturalyianni** [comment]
Thank you for your reply!

This happens with the "hallucination" protocol as well. 

This also happens regardles of the target that i am using as my input PDB file.

**Comment by victorconan** [comment]
same error when running the `peptide_binder_design.ipynb`:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [7], line 25
     22   pssm = softmax(model._tmp["seq_logits"],-1)
     24 if optimizer == "pssm_semigreedy":
---> 25   model.design_pssm_semigreedy(120, 32, **flags)
     26   pssm = softmax(model._tmp["seq_logits"],1)
     28 if optimizer == "semigreedy":

File ~/miniconda3/envs/p39/lib/python3.9/site-packages/colabdesign/af/design.py:441, in _af_design.design_pssm_semigreedy(self, soft_iters, hard_iters, tries, ramp_recycles, ramp_models, **kwargs)
    436 def design_pssm_semigreedy(self, soft_iters=300, hard_iters=32, tries=10,
    437                            ramp_recycles=True, ramp_models=True, **kwargs):
    438 
    439   # stage 1: logits -> softmax(logits)
    440   if soft_iters > 0:
--> 441     self.design_3stage(soft_iters, 0, 0, ramp_recycles=ramp_recycles, **kwargs)
    442     self._tmp["seq_logits"] = kwargs["seq_logits"] = self.aux["seq"]["logits"]
    444   # stage 2: semi_greedy

File ~/miniconda3/envs/p39/lib/python3.9/site-packages/colabdesign/af/design.py:362, in _af_design.design_3stage(self, soft_iters, temp_iters, hard_iters, ramp_recycles, **kwargs)
    360     kwargs["num_recycles"] = c
    361     iters = soft_iters // num_cycles
--> 362     self.design_logits(iters, soft=c*p, e_soft=(c+1)*p, **kwargs)        
    363 else:
    364   self.design_logits(soft_iters, e_soft=1, **kwargs)
...
--> 107 auxs = jax.tree_map(lambda *x: np.stack(x), *auxs)
    109 # update aux
    110 aux = jax.tree_map(lambda x:x[0], auxs)

TypeError: tree_map() missing 1 required positional argument: 'tree'
```

**Comment by sokrypton** [comment]
what version of jax are you using?

**Comment by victorconan** [comment]
> what version of jax are you using?

0.3.17

**Comment by sokrypton** [comment]
and jaxlib?

**Comment by victorconan** [comment]
> and jaxlib?

0.3.15

**Comment by sokrypton** [comment]
Hmmmm... the only reason I can think why this would fail is if the model params were not loaded.

Did you get this warning at the top of the script?
```
WARNING: 'model_1_ptm' not found
WARNING: 'model_2_ptm' not found
WARNING: 'model_3_ptm' not found
WARNING: 'model_4_ptm' not found
WARNING: 'model_5_ptm' not found
```

If so, you'll need to manually specify the location of the params:
```python
model = mk_afdesign_model(..., data_dir="/location/of/params")
```

**Comment by victorconan** [comment]
This works! Thanks!

**Comment by sokrypton** [comment]
Yay! @unnaturalyianni does specifying path to params fix the problem?

**Comment by victorconan** [comment]
> Yay! @unnaturalyianni does specifying path to params fix the problem?

Yes! Specifying the path fixed the problem!

**Comment by unnaturalyianni** [comment]
Thank you for all your comments!

I am also using the above versions of jax and jaxlib. However i am unable to locate the parameters of the model?

How can i get access to that?

**Comment by unnaturalyianni** [comment]
@ sokrypton

**Comment by victorconan** [comment]
> Thank you for all your comments!
> 
> I am also using the above versions of jax and jaxlib. However i am unable to locate the parameters of the model?
> 
> How can i get access to that?

You have specify the path to data_dir in 
```
model = mk_afdesign_model(protocol="binder",
                            use_multimer=x["use_multimer"],
                            num_recycles=num_recycles,
                            recycle_mode="sample",
                            data_dir="<specify params folder path here>")
```

**Comment by unnaturalyianni** [comment]
I understand, but the repo is not providing these parameter files.

Where can i find those?

**Comment by sokrypton** [comment]
@unnaturalyianni 
```bash
# download alphafold weights
mkdir params
curl -fsSL https://storage.googleapis.com/alphafold/alphafold_params_2022-03-02.tar | tar x -C params
```
